name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile
      - run: lerna run build

  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: npm i -g yarn
      - uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile --focus

      - name: Build server image
        run: docker-compose build server

